name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Your Files
        uses: actions/checkout@v4

      - name: Prepare Theos
        uses: randomblock1/theos-action@v1

      - name: Build Package
        run: |
          make package FINALPACKAGE=1
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DeltaMaster-Dylib
          path: packages/*.deb
