name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    # خطوة تحميل الملفات
    - name: Checkout Your Files
      uses: actions/checkout@v4

    # تثبيت Theos
    - name: Install Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV

    # التحقق من تثبيت Theos بنجاح
    - name: Verify Theos Installation
      run: |
        echo $THEOS
        ls -l $THEOS

    # تثبيت الأدوات المطلوبة
    - name: Install Dependencies
      run: |
        brew install libtool automake autoconf perl
        brew install python3
        brew install llvm
        brew install make
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

    # التحقق من تثبيت الأدوات بنجاح
    - name: Verify Dependencies Installation
      run: |
        brew list libtool automake autoconf python3 perl
        which clang
        which make

    # تحديد المسارات البيئية
    - name: Set environment variables
      run: |
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "THEOS_TOOLCHAIN=/usr/bin/clang" >> $GITHUB_ENV
        echo "PATH=$HOME/theos/bin:$PATH" >> $GITHUB_ENV

    # تنظيف وإعادة بناء الحزمة
    - name: Clean and Build Package
      run: |
        make clean
        make package FINALPACKAGE=1
      env:
        THEOS: $HOME/theos
        THEOS_TOOLCHAIN: /usr/bin/clang
        PATH: $HOME/theos/bin:$PATH

    # التحقق من وجود الحزمة بعد البناء
    - name: List built packages
      run: |
        ls -l packages/*.deb

    # رفع الحزمة
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DeltaMaster-Dylib
        path: packages/*.deb